name: moe-parkour

services:
  isaacgym:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: isaacgym:latest
    working_dir: /home/gymuser
    command: /bin/bash
    stdin_open: true
    tty: true
    ipc: host
    network_mode: host
    gpus: all
    environment:
      DISPLAY: ${DISPLAY:-}
      PATH: /opt/conda/bin:/usr/local/nvm/versions/node/v16.6.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
      PYTHONPATH: /opt/isaacgym/python:/home/gymuser/rl_lib:/home/gymuser/robot_firmware
    volumes:
      - ${ISAACGYM_ROOT:-./isaacgym}/python:/opt/isaacgym/python:ro
      - ./docker_mount:/docker_mount
      - ./extreme-parkour:/home/gymuser/extreme-parkour
      - ./rl_lib:/home/gymuser/rl_lib
      - ./robot_firmware:/home/gymuser/robot_firmware
      - /tmp/.X11-unix:/tmp/.X11-unix
